server:
  contextPath: /zuul-ab-test

zuul:
  routes:
    default:
      path: /**
      url: https://www.bbva.cl

ribbon:
  eureka:
    enabled: false

testa:
  url: https://www.bbva.cl

testb:
  url: https://www.scotiabankchile.cl
  ruts:
    - rut: 1-9
    - rut: 1-8
    - rut: 1-0
    
    